use metadata file in release instead of version file

diff --git a/.github/workflows/poll_game_update.yml b/.github/workflows/poll_game_update.yml
--- a/.github/workflows/poll_game_update.yml
+++ b/.github/workflows/poll_game_update.yml
@@ -21,19 +21,28 @@ jobs:
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
-      - name: Fetch VERSION file of last release
+      - name: Read version from metadata file of last release
         id: fetch_last_release_version
         run: |
+          $FileToDownload='release.zip'
           $ResponseString=@'
           ${{ steps.fetch_last_release.outputs.data }}
           '@
           $Response=($ResponseString | ConvertFrom-Json)
-          $VersionAsset=($Response.assets | Where-Object {$_.name -eq 'VERSION'})[0]
-          $Url=$VersionAsset.browser_download_url
-          echo "Last release VERSION file: $Url"
-          $Version=$(Invoke-WebRequest -Uri "$Url")
-          echo "Last release version: $Version"
-          echo "version=$Version" >> $Env:GITHUB_OUTPUT
+          $ReleaseAsset=($Response.assets | Where-Object {$_.name -eq $FileToDownload})[0]
+          $Url=$ReleaseAsset.browser_download_url
+          echo "Asset file: $Url"
+          $null=Invoke-WebRequest -Uri "$Url" -OutFile $FileToDownload
+          $null=7z x $FileToDownload -orelease
+          
+          if (!Test-Path 'release/DofusBatteriesIncluded/metadata.json') {
+            $null=Write-Error "Could not find metadata file in last release." 
+            exit 1
+          }
+          
+          $Metadata=(Get-Content 'release/DofusBatteriesIncluded/metadata.json' | Out-String | ConvertFrom-Json)
+          echo "Last release version: $(Metadata.GameVersion)"
+          echo "version=$(Metadata.GameVersion)" >> $Env:GITHUB_OUTPUT
 
       - name: Setup Node
         uses: actions/setup-node@v4
